Frist Commit
fortinet-fortisoar/solution-pack-phishing-email-triage-based-on-ml-classifier pull request #1
Opened 2022-06-21 05:48 UTC by cs-sujeet-ahirrao

Frist Commit

2022-06-21 07:58 UTC, cs-suyog-jinturkar commented on docs/setup.md
> +The **PPhishing Email Triage Based On ML Classifier** solution pack depends on the following solution packs that are installed automatically &ndash; if not already installed.
Spelling mistake

2022-06-21 07:58 UTC, cs-suyog-jinturkar commented on docs/setup.md
> +For optimal performance of **PPhishing Email Triage Based On ML Classifier** solution pack, you can install and configure:
Spelling mistake

2022-06-21 08:00 UTC, cs-suyog-jinturkar reviewed
Added review comments

2022-06-21 08:01 UTC, cs-suyog-jinturkar commented
Please make sure document is correct and this SP installs properly

2022-06-22 06:42 UTC, cs-abhishek-shukla requested changes

2022-06-22 06:42 UTC, cs-abhishek-shukla commented on README.md
> +The **Phishing Email Triage Based On ML Classifier Solution Pack** demonstrates the scenarios and Triage playbook around phishing emails based on using the information provided through email server.
The **Phishing Email Triage Based on ML Classifier** Solution Pack demonstrates the scenarios and triage playbooks around phishing emails, using the information provided through the email server.

2022-06-22 06:42 UTC, cs-abhishek-shukla commented on README.md
> +It provides a set of triage playbook that you can use to take the triaging action on phishing emails and also comes with a scenario that demonstrates and generates a demo alert for the Alert Type 'Ph
The triage playbooks help perform triage on phishing emails, and the included scenario demonstrates and generates a demo alert of the type **Phishing**.

2022-06-22 06:42 UTC, cs-abhishek-shukla commented on README.md
> +The triage playbook take the triaging action on the phishing email.
This line is repetitive and can be removed.

2022-06-22 06:42 UTC, cs-abhishek-shukla commented on README.md
> +* Configure the threshold value for in the "Configuration" step. Threshold identifies the confidence level above which we are sure that the email is phishing.
This information is already present in Usage section and can be removed from here

2022-06-22 06:42 UTC, cs-abhishek-shukla commented on README.md
> +* Classify the phishing email using the FortiSOAR Phishing Classifier connector.
This information is already present in Usage section and can be removed from here

2022-06-22 06:42 UTC, cs-abhishek-shukla commented on README.md
> +* Based on the phising classifier output raise the record sevirity to malicious.
This information is already present in Usage section and can be removed from here

2022-06-22 06:42 UTC, cs-abhishek-shukla commented on docs/contents.md
> +|**Name**|**Description**|
Since it is a table header, specified by `:-`, we do not need `**` before `Name` and `Description`

2022-06-22 06:42 UTC, cs-abhishek-shukla commented on docs/contents.md
> +|02 - 02 - Use Case - Phishing Email Triage Based On ML Classifier |
`02 - 02` twice. Is it the name of the playbook?

2022-06-22 06:42 UTC, cs-abhishek-shukla commented on docs/setup.md
> +| **Solution Pack Name** | **Purpose**   |
Since it is a table header, specified by `:-`, we do not need `**` before `Solution Pack Name` and `Purpose`

2022-06-22 06:42 UTC, cs-abhishek-shukla commented on docs/usage.md
> +- Users can execute investigation playbook, out-of-the-box (OOB), against the alert **Phishing Email Triage Based On ML Classifier**. It utilizes email information (sender, receiver, subject, body, h
Is this the name of the alert?

2022-06-22 06:42 UTC, cs-abhishek-shukla commented on docs/usage.md
> +- Set the threshold value for confidence. Threshold identifies the confidence level above which we are sure that the email is phishing.
... above which we can be sure that this email is a phishing email.

2022-06-22 06:42 UTC, cs-abhishek-shukla commented on docs/usage.md
> +- Provide verdict for the phising alert record to the FortiSOAR Phishing Classifier connector, which will return the "confidence", "status" and "label" as a response.
- Provide verdict for the phishing alert record to the FortiSOAR Phishing Classifier connector, which returns the **confidence**, **status**, and **label** as a response.

2022-06-22 06:42 UTC, cs-abhishek-shukla commented on docs/usage.md
> +- Based on the response parameters and threshold value the triage action will perform.
- The triaging takes into account the response parameter and the threshold value

2022-06-22 07:23 UTC, cs-sujeet-ahirrao commented on docs/setup.md
> +The **PPhishing Email Triage Based On ML Classifier** solution pack depends on the following solution packs that are installed automatically &ndash; if not already installed.
Doone

2022-06-22 07:23 UTC, cs-sujeet-ahirrao commented on docs/setup.md
> +For optimal performance of **PPhishing Email Triage Based On ML Classifier** solution pack, you can install and configure:
Done

2022-06-22 07:24 UTC, cs-sujeet-ahirrao commented on docs/setup.md
> +| **Solution Pack Name** | **Purpose**   |
Done

2022-06-22 07:30 UTC, cs-sujeet-ahirrao commented on README.md
> +The **Phishing Email Triage Based On ML Classifier Solution Pack** demonstrates the scenarios and Triage playbook around phishing emails based on using the information provided through email server.
Done

2022-06-22 07:30 UTC, cs-sujeet-ahirrao commented on README.md
> +It provides a set of triage playbook that you can use to take the triaging action on phishing emails and also comes with a scenario that demonstrates and generates a demo alert for the Alert Type 'Ph
Done

2022-06-22 07:31 UTC, cs-sujeet-ahirrao commented on README.md
> +The triage playbook take the triaging action on the phishing email.
Done

2022-06-22 07:31 UTC, cs-sujeet-ahirrao commented on README.md
> +* Configure the threshold value for in the "Configuration" step. Threshold identifies the confidence level above which we are sure that the email is phishing.
Done

2022-06-22 07:32 UTC, cs-sujeet-ahirrao commented on README.md
> +* Based on the phising classifier output raise the record sevirity to malicious.
Done

2022-06-22 07:32 UTC, cs-sujeet-ahirrao commented on README.md
> +* Classify the phishing email using the FortiSOAR Phishing Classifier connector.
Done

2022-06-22 07:50 UTC, cs-sujeet-ahirrao commented on docs/contents.md
> +|**Name**|**Description**|
Done

2022-06-22 07:51 UTC, cs-sujeet-ahirrao commented on docs/contents.md
> +|02 - 02 - Use Case - Phishing Email Triage Based On ML Classifier |
Done

2022-06-22 07:53 UTC, cs-sujeet-ahirrao commented on docs/usage.md
> +- Users can execute investigation playbook, out-of-the-box (OOB), against the alert **Phishing Email Triage Based On ML Classifier**. It utilizes email information (sender, receiver, subject, body, h
These are the email fields

2022-06-22 07:53 UTC, cs-sujeet-ahirrao commented on docs/usage.md
> +- Set the threshold value for confidence. Threshold identifies the confidence level above which we are sure that the email is phishing.
yes its Phishing email

2022-06-22 07:54 UTC, cs-sujeet-ahirrao commented on docs/usage.md
> +- Provide verdict for the phising alert record to the FortiSOAR Phishing Classifier connector, which will return the "confidence", "status" and "label" as a response.
Done

2022-06-22 07:55 UTC, cs-sujeet-ahirrao commented on docs/usage.md
> +- Based on the response parameters and threshold value the triage action will perform.
Done

2022-06-22 10:09 UTC, cs-abhishek-shukla requested changes

2022-06-22 10:09 UTC, cs-abhishek-shukla commented on README.md
> +The triage playbooks help perform triage on phishing emails, and the included scenario demonstrates and generates a demo alert of the type Phishing.
type **Phishing**

'Phishing' in bold.

2022-06-22 10:09 UTC, cs-abhishek-shukla commented on docs/contents.md
> +|Name|Descriptio|
Description... 'n' missing

2022-06-22 11:06 UTC, cs-sujeet-ahirrao commented on README.md
> +The triage playbooks help perform triage on phishing emails, and the included scenario demonstrates and generates a demo alert of the type Phishing.
Done

2022-06-23 10:11 UTC, cs-sujeet-ahirrao commented on docs/contents.md
> +|Name|Descriptio|
Done

2022-06-23 10:19 UTC, cs-suyog-jinturkar approved these changes

2022-06-23 10:55 UTC, merged